version: '3.8'

services:
  voice-ai-demo:
    build: .
    container_name: voice-ai-demo
    ports:
      - "8080:8080"
    environment:
      # ElevenLabs API 키 (환경변수로 설정)
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      # Spring Boot 설정
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    volumes:
      # 로그 디렉토리 마운트 (선택사항)
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/voice/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - voice-ai-network

networks:
  voice-ai-network:
    driver: bridge 